Repository xenserver/xenadmin, pull requests merged in 2018-10, with the labels that each got.

#2226 CA-287643: Replaced list view with data grid view to resolve column sizing issue and for consistency with the rest of the product.
  XenAdmin/Commands/EditTagsCommand.cs
  XenAdmin/Controls/DataGridViewEx/DataGridViewEx.cs
  XenAdmin/Controls/Tags/TagList.cs
  XenAdmin/Dialogs/NewTagDialog.Designer.cs
  XenAdmin/Dialogs/NewTagDialog.cs
  XenAdmin/Dialogs/NewTagDialog.resx
  XenAdminTests/CommandTests/EditTagsCommandTest.cs
  XenAdminTests/MainWindowWrapper/NewTagDialogWrapper.cs
Labels: updated

#2243 CP-29276: Add option to specify an update/supp pack in RPU wizard
  XenAdmin/Wizards/PatchingWizard/AutomatedUpdatesBasePage.cs
  XenAdmin/Wizards/RollingUpgradeWizard/PlanActions/RpuUploadAndApplySuppPackPlanAction.cs
  XenAdmin/Wizards/RollingUpgradeWizard/RollingUpgradeReadyToUpgradePage.Designer.cs
  XenAdmin/Wizards/RollingUpgradeWizard/RollingUpgradeReadyToUpgradePage.cs
  XenAdmin/Wizards/RollingUpgradeWizard/RollingUpgradeReadyToUpgradePage.resx
  XenAdmin/Wizards/RollingUpgradeWizard/RollingUpgradeUpgradePage.cs
  XenAdmin/Wizards/RollingUpgradeWizard/RollingUpgradeWizard.cs
  XenAdmin/Wizards/RollingUpgradeWizard/RollingUpgradeWizard_SelectInstallMethod.Designer.cs
  XenAdmin/Wizards/RollingUpgradeWizard/RollingUpgradeWizard_SelectInstallMethod.cs
  XenAdmin/Wizards/RollingUpgradeWizard/RollingUpgradeWizard_SelectInstallMethod.resx
  XenAdmin/XenAdmin.csproj
Labels: updated

#2236 CA-298954: Match server branding and version.
  XenModel/Messages.Designer.cs
  XenModel/Messages.resx
  XenModel/XenAPI-Extensions/Host.cs
Labels: updated

#2270 CP-14807: Delete OEM in ServerVersion
  XenAdmin/Actions/GUIActions/IgnorePatchAction.cs
  XenAdmin/Actions/GUIActions/IgnoreServerAction.cs
  XenAdmin/Actions/GUIActions/RestoreDismissedUpdatesAction.cs
  XenAdmin/Alerts/Types/XenServerPatchAlert.cs
  XenAdmin/Alerts/Types/XenServerVersionAlert.cs
  XenAdmin/Core/Updates.cs
  XenAdmin/XenAdmin.csproj
  XenAdminTests/UnitTests/BatchUpdatesTests/BatchUpdatesTests.cs
  XenModel/Actions/Updates/XenServerVersion.cs
  XenModel/Utils/Helpers.cs
Labels: updated

#2273 CA-298921: End of error message in XenCenter is cut off when failed t…
  XenAdmin/Dialogs/CommandErrorDialog.Designer.cs
  XenAdmin/Dialogs/CommandErrorDialog.resx
Labels: needs updating

#2272 CA-203431: Host name is repeated twice in multipathing alert message in XC
  XenAdmin/Alerts/Types/MessageAlert.cs
  XenAdminTests/UnitTests/AlertTests/MultipathAlertTest.cs
  XenAdminTests/XenAdminTests.csproj
Labels: under review, updated

#2253 CA-293814: If there are no VMs running, immediately start entering Ma…
  XenAdmin/Commands/HostMaintenanceModeCommand.cs
Labels: updated
