Repository xenserver/xenadmin, pull requests merged in 2018-03, with the labels that each got.

#1941 CA-272150: Optimize destination page of cross-pool-migrate wizard.
  XenAdmin/Wizards/CrossPoolMigrateWizard/CrossPoolMigrateDestinationPage.cs
  XenAdmin/Wizards/CrossPoolMigrateWizard/Filters/CrossPoolMigrateCanMigrateFilter.cs
  XenAdmin/Wizards/GenericPages/DelayLoadingOptionComboBoxItem.cs
  XenAdmin/Wizards/GenericPages/ReasoningFilter.cs
  XenAdmin/Wizards/GenericPages/SelectMultipleVMDestinationPage.cs
Labels: updated

#1954 CP-26421: Remove SR-IOV network on host's Networking TabPage
  XenModel/Actions/Network/NetworkAction.cs
  XenModel/XenAPI-Extensions/PIF.cs
Labels: needs updating

#1966 CA-284095: Fix sort-by creation date
  XenAdmin/TabPages/SnapshotsPage.cs
Labels: updated

#1937 CA-274082: Check status of SR uploaded updates during update installa…
  XenAdmin/Diagnostics/Checks/PBDsPluggedCheck.cs
  XenAdmin/Diagnostics/Checks/PatchPrecheckCheck.cs
  XenAdmin/Diagnostics/Problems/SRProblem/BrokenSR.cs
  XenAdmin/Dialogs/RepairSRDialog.cs
  XenAdmin/Wizards/PatchingWizard/PatchingWizard.cs
  XenAdmin/Wizards/PatchingWizard/PatchingWizard_PrecheckPage.cs
  XenAdmin/Wizards/PatchingWizard/PatchingWizard_UploadPage.cs
  XenModel/Actions/SupplementalPack/UploadSupplementalPackAction.cs
  XenModel/Messages.Designer.cs
  XenModel/Messages.resx
Labels: reviewed, updated

#1975 CP-25990: Enable Create VLAN on SR-IOV network
  XenAdmin/Wizards/NewNetworkWizard.cs
  XenAdmin/Wizards/NewNetworkWizard_Pages/NetWDetails.Designer.cs
  XenAdmin/Wizards/NewNetworkWizard_Pages/NetWDetails.cs
  XenAdmin/Wizards/NewNetworkWizard_Pages/NetWDetails.resx
Labels: needs updating

#1980 CP-26884: add network-sriov info in OVF file when exporting vm
  XenAdmin/Controls/NetworkingTab/NetworkList.cs
  XenAdmin/Dialogs/VIFDialog.cs
  XenModel/XenAPI-Extensions/VM.cs
  XenOvfTransport/Export.cs
Labels: needs updating

#1982 CP-26363: Display the remaining VF numbers in NIC TabPage
  XenAdmin/Controls/NetworkingTab/NetworkList.cs
  XenAdmin/TabPages/NICPage.cs
  XenAdmin/Wizards/NewNetworkWizard.cs
  XenModel/Actions/Network/NetworkAction.cs
  XenModel/Messages.Designer.cs
  XenModel/Messages.resx
  XenModel/XenAPI-Extensions/Network.cs
  XenModel/XenAPI-Extensions/PIF.cs
Labels: needs updating

#1985 CA-284226: Optimize performance of menu Start-on-Server and Migrate-to-Server
  XenAdmin/Commands/Controls/VMOperationToolStripMenuItem.cs
  XenAdmin/Commands/Controls/VMOperationToolStripMenuSubItem.cs
  XenAdmin/Controls/VisualMenuItem.cs
  XenModel/Actions/ProduceConsumerQueue.cs
Labels: updated

#1986 CA-285268: Patching Wizard improvement: Read metadata from the update…
  XenAdmin/Core/Updates.cs
  XenAdmin/Wizards/PatchingWizard/PatchingWizard_SelectPatchPage.cs
Labels: updated

#1997 CA-281652: Add VM_REQUIRES_GPU failure reason
  XenAdmin/Diagnostics/Checks/AssertCanEvacuateCheck.cs
  XenAdmin/Diagnostics/Problems/VMProblem/CannotMigrateVM.cs
  XenModel/Messages.Designer.cs
  XenModel/Messages.resx
  XenModel/XenAPI-Extensions/Failure.cs
Labels: updated

#2010 CA-286458: Fix latestcr XC requirement when apply CR update
  XenAdmin/Core/Updates.cs
  XenAdminTests/UnitTests/AlertTests/XenServerUpdateAlertTests.cs
  XenAdminTests/UnitTests/BatchUpdatesTests/BatchUpdatesTests.cs
  XenModel/Actions/Updates/DownloadUpdatesXmlAction.cs
  XenModel/Actions/Updates/XenServerVersion.cs
Labels: updated
