Repository xenserver/xenadmin, pull requests merged in 2018-11, with the labels that each got.

#2284 CA-237915: When one attempts logging oneself out, warn them if there are outstanding actions.
  XenAdmin/TabPages/AdPage.cs
  XenAdmin/TabPages/HistoryPage.cs
  XenModel/Messages.Designer.cs
  XenModel/Messages.resx
Labels: reviewed

#2295 CA-301501: Update the progress bar for the action uploading a server status report.
  XenModel/Actions/HealthCheck/UploadServerStatusReportAction.cs
  XenModel/Actions/HealthCheck/XenServerHealthCheckUpload.cs
  XenModel/Messages.Designer.cs
  XenModel/Messages.resx
  XenServerHealthCheck/XenServerHealthCheckBundleUpload.cs
Labels: reviewed

#2283 CP-29768: Add Skip functionality for RPU supp pack installation
  XenAdmin/Wizards/PatchingWizard/AutomatedUpdatesBasePage.cs
  XenAdmin/Wizards/PatchingWizard/AutomatedUpdatesBasePage.designer.cs
  XenAdmin/Wizards/PatchingWizard/AutomatedUpdatesBasePage.resx
  XenAdmin/Wizards/PatchingWizard/PlanActions/PlanAction.cs
  XenAdmin/Wizards/PatchingWizard/PlanActions/PlanActionWithSession.cs
  XenAdmin/Wizards/PatchingWizard/PlanActions/RemoveUpdateFilesFromMaster.cs
  XenAdmin/Wizards/PatchingWizard/UpdateProgressBackgroundWorker.cs
  XenAdmin/Wizards/RollingUpgradeWizard/PlanActions/RpuUploadAndApplySuppPackPlanAction.cs
  XenModel/Messages.Designer.cs
  XenModel/Messages.resx
Labels: under review, updated

#2311 CA-301156: VM created from disk import for a UEFI VM has missing values
  XenAdmin/Wizards/ImportWizard/ImportWizard.cs
Labels: question

#2287 CA-290940: Versions newer than those we have on record should be int…
  XenAdmin/Wizards/PatchingWizard/PatchingWizard_SelectServers.cs
Labels: reviewed

#2330 XOP-953: Cannot change dom0 memory via XenCenter (XC 7.5 RTM on XS 7.…
  XenAdmin/Dialogs/ControlDomainMemoryDialog.cs
  XenModel/Actions/Host/ChangeControlDomainMemoryAction.cs
  XenModel/Messages.Designer.cs
  XenModel/Messages.resx
  XenModel/XenAPI-Extensions/Failure.cs
Labels: updated

#2318 CA-300384: XC unable to create (GFS2) VDI of virtual-size larger than…
  XenAdmin/Wizards/NewVMWizard/Page_Storage.cs
Labels: updated
