Repository xenserver/xenadmin, pull requests merged in 2021-08, with the labels that each got.

#2852 Bumped pipeline version.
  Jenkinsfile
Labels: 2 approvals

#2853 Bumped pipeline version and commented out ignored test.
  Jenkinsfile
  XenAdminTests/Controls/Folders/FolderListItemTests.cs
Labels: 2 approvals

#2844 CA-279581: Prevent panel headers from overlapping scrollbar
  XenAdmin/TabPages/GeneralTabPage.Designer.cs
  XenAdmin/TabPages/GeneralTabPage.cs
Labels: 2 approvals

#2851 Updated hall of fame.
  XenAdmin/TestResources/credits.xml
Labels: 2 approvals

#2821 CA-340735: Re-wrote Page_InstallationMedia of the NewVM wizard to fix various issues
  XenAdmin/Controls/ComboBoxes/CDChanger.cs
  XenAdmin/Controls/ComboBoxes/ISODropDownBox.cs
  XenAdmin/Controls/MultipleDvdIsoList.Designer.cs
  XenAdmin/Controls/MultipleDvdIsoList.cs
  XenAdmin/Wizards/NewVMWizard/NewVMWizard.cs
  XenAdmin/Wizards/NewVMWizard/Page_InstallationMedia.Designer.cs
  XenAdmin/Wizards/NewVMWizard/Page_InstallationMedia.cs
  XenAdmin/Wizards/NewVMWizard/Page_InstallationMedia.resx
  XenModel/Utils/Helpers.cs
Labels: 2 approvals

#2824 Some code removal and workflow fixes around WLB reports (includes CA-339666).
  XenAdmin/Commands/ViewWorkloadReportsCommand.cs
  XenAdmin/Controls/Wlb/WlbOptModeScheduler.cs
  XenAdmin/Controls/Wlb/WlbOptimizePool.cs
  XenAdmin/Controls/Wlb/WlbReportSubscriptionView.cs
  XenAdmin/Controls/Wlb/WlbReportView.cs
  XenAdmin/Dialogs/Wlb/WlbConfigurationDialog.Designer.cs
  XenAdmin/Dialogs/Wlb/WorkloadReports.Designer.cs
  XenAdmin/Dialogs/Wlb/WorkloadReports.cs
  XenAdmin/Dialogs/Wlb/WorkloadReports.ja.resx
  XenAdmin/Dialogs/Wlb/WorkloadReports.resx
  XenAdmin/Dialogs/Wlb/WorkloadReports.zh-CN.resx
  XenAdmin/TestResources/api-version.xml
  XenAdmin/TestResources/dummyheader.txt
  XenAdmin/XenAdmin.csproj
  XenAdminTests/SearchTests/XenSearchQueryTest.cs
  XenAdminTests/UnitTests/WlbTests/WlbScheduledTaskTests.cs
  XenAdminTests/XenAdminTests.csproj
  XenModel/Messages.Designer.cs
  XenModel/Messages.resx
  XenModel/WLB/RetrieveWlbConfigurationAction.cs
  XenModel/WLB/WlbPoolConfiguration.cs
  XenModel/WLB/WlbReportAction.cs
  XenModel/WLB/WlbReportInfo.cs
  XenModel/WLB/WlbReportSubscription.cs
  XenModel/WLB/WlbScheduledTask.cs
  XenModel/XenModel.csproj
Labels: 2 approvals

#2848 CP-36567: Use the datasource units specified in the API.
  XenAdmin/Controls/CustomDataGraph/ArchiveMaintainer.cs
  XenAdmin/Controls/CustomDataGraph/DataArchive.cs
  XenAdmin/Controls/CustomDataGraph/DataKey.cs
  XenAdmin/Controls/CustomDataGraph/DataPlot.cs
  XenAdmin/Controls/CustomDataGraph/DataPlotNav.cs
  XenAdmin/Controls/CustomDataGraph/DataRange.cs
  XenAdmin/Controls/CustomDataGraph/DataSet.cs
  XenAdmin/Controls/CustomDataGraph/GraphHelpers.cs
  XenAdmin/Controls/CustomDataGraph/GraphList.cs
  XenAdmin/Controls/CustomDataGraph/Palette.cs
  XenAdmin/Dialogs/GraphDetailsDialog.cs
  XenModel/UnitStrings.Designer.cs
  XenModel/UnitStrings.ja.resx
  XenModel/UnitStrings.resx
  XenModel/UnitStrings.zh-CN.resx
  XenModel/Utils/Helpers.cs
  XenModel/Utils/Util.cs
  XenModel/XenModel.csproj
Labels: 2 approvals

#2846 CA-339590: Add conditional page control refresh in HA Wizard
  XenAdmin/Dialogs/EditVmHaPrioritiesDialog.cs
  XenAdmin/Wizards/HAWizard_Pages/AssignPriorities.cs
Labels: 1 approval

#2855 Replaced travis build with github actions. Updated maintainers.
  .github/workflows/main.yml
  .travis.yml
  MAINTAINERS
  README.md
Labels: 1 approval

#2850 Tidy up config files
  XenAdminTests/Properties/AssemblyInfo.cs
  XenAdminTests/XenAdminTests.csproj
  XenAdminTests/app.config
  XenCenterLib/XenCenterLib.csproj
  XenCenterLib/app.config
  XenModel/Actions/OvfActions/ImportApplianceAction.cs
  XenOvfApi/Conversions.cs
  XenOvfApi/OVF.cs
  XenOvfApi/Package.cs
  XenOvfApi/Properties/Settings.Designer.cs
  XenOvfApi/Properties/Settings.settings
  XenOvfApi/Security.cs
  XenOvfApi/Utilities/Utilities.cs
  XenOvfApi/Utilities/ValueMaps.cs
  XenOvfApi/Validation.cs
  XenOvfApi/XenOvfApi.csproj
  XenOvfApi/app.config
Labels: 2 approvals

#2857 Fixed broken build
  scripts/re-branding.sh
Labels: 1 approval

#2841 CA-349435 - Fixed tooltip display on Options and Properties dialogs
  XenAdmin/Controls/UpsellPage.cs
  XenAdmin/Dialogs/OptionsDialog.Designer.cs
  XenAdmin/Dialogs/OptionsDialog.cs
  XenAdmin/Dialogs/OptionsDialog.resx
  XenAdmin/Dialogs/OptionsPages/ConfirmationOptionsPage.cs
  XenAdmin/Dialogs/OptionsPages/ConnectionOptionsPage.cs
  XenAdmin/Dialogs/OptionsPages/ConsolesOptionsPage.cs
  XenAdmin/Dialogs/OptionsPages/DisplayOptionsPage.cs
  XenAdmin/Dialogs/OptionsPages/IOptionsPage.cs
  XenAdmin/Dialogs/OptionsPages/PluginOptionsPage.cs
  XenAdmin/Dialogs/OptionsPages/SaveAndRestoreOptionsPage.cs
  XenAdmin/Dialogs/OptionsPages/SecurityOptionsPage.cs
  XenAdmin/Dialogs/OptionsPages/UpdatesOptionsPage.cs
  XenAdmin/Dialogs/PropertiesDialog.cs
  XenAdmin/Dialogs/PvsPages/PvsCacheConfigurationPage.cs
  XenAdmin/SettingsPanels/BootOptionsEditPage.cs
  XenAdmin/SettingsPanels/CPUMemoryEditPage.cs
  XenAdmin/SettingsPanels/ClusteringEditPage.cs
  XenAdmin/SettingsPanels/CustomFieldsDisplayPage.cs
  XenAdmin/SettingsPanels/EditNetworkPage.cs
  XenAdmin/SettingsPanels/GeneralEditPage.cs
  XenAdmin/SettingsPanels/GpuEditPage.cs
  XenAdmin/SettingsPanels/HomeServerEditPage.cs
  XenAdmin/SettingsPanels/HostMultipathPage.cs
  XenAdmin/SettingsPanels/HostPowerONEditPage.cs
  XenAdmin/SettingsPanels/IEditPage.cs
  XenAdmin/SettingsPanels/LivePatchingEditPage.cs
  XenAdmin/SettingsPanels/LogDestinationEditPage.cs
  XenAdmin/SettingsPanels/NetworkOptionsEditPage.cs
  XenAdmin/SettingsPanels/PerfmonAlertEditPage.cs
  XenAdmin/SettingsPanels/PerfmonAlertOptionsPage.cs
  XenAdmin/SettingsPanels/PoolGpuEditPage.cs
  XenAdmin/SettingsPanels/SecurityEditPage.cs
  XenAdmin/SettingsPanels/SrReadCachingEditPage.cs
  XenAdmin/SettingsPanels/USBEditPage.cs
  XenAdmin/SettingsPanels/VBDEditPage.cs
  XenAdmin/SettingsPanels/VDISizeLocationPage.cs
  XenAdmin/SettingsPanels/VMAdvancedEditPage.cs
  XenAdmin/SettingsPanels/VMEnlightenmentEditPage.cs
  XenAdmin/SettingsPanels/VMHAEditPage.cs
  XenAdmin/SettingsPanels/Wlb/WlbAdvancedSettingsPage.cs
  XenAdmin/SettingsPanels/Wlb/WlbAutomationPage.cs
  XenAdmin/SettingsPanels/Wlb/WlbHostExclusionPage.cs
  XenAdmin/SettingsPanels/Wlb/WlbMetricWeightingPage.cs
  XenAdmin/SettingsPanels/Wlb/WlbOptimizationModePage.cs
  XenAdmin/SettingsPanels/Wlb/WlbThresholdsPage.cs
  XenAdmin/Wizards/GenericPages/NewVMGroupVMsPage.cs
  XenAdmin/Wizards/GenericPages/NewVMGroupVMsPageBase.cs
  XenAdmin/Wizards/NewPolicyWizard/NewPolicySnapshotFrequencyPage.cs
  XenAdmin/Wizards/NewPolicyWizard/NewPolicySnapshotTypePage.cs
  XenAdmin/Wizards/NewVMApplianceWizard/NewVMApplianceNamePage.cs
  XenAdmin/Wizards/NewVMApplianceWizard/NewVMApplianceVMOrderAndDelaysPage.cs
  XenAdmin/Wizards/NewVMWizard/Page_CloudConfigParameters.cs
Labels: needs updating

#2847 CA-310974: Hide GPU page if the host has no GPU capability
  XenAdmin/Dialogs/AddVGPUDialog.cs
  XenAdmin/Dialogs/PropertiesDialog.cs
  XenAdmin/SettingsPanels/GpuEditPage.cs
  XenAdmin/Wizards/NewVMWizard/NewVMWizard.cs
  XenModel/Messages.Designer.cs
  XenModel/Messages.resx
  XenModel/Utils/Helpers.cs
Labels: 2 approvals

#2849 CA-260319: Show warning in Health Check if connected with less privileged RBAC User
  XenAdmin/Core/HealthCheck.cs
  XenAdmin/Dialogs/HealthCheck/HealthCheckOverviewDialog.Designer.cs
  XenAdmin/Dialogs/HealthCheck/HealthCheckOverviewDialog.cs
  XenAdmin/Dialogs/HealthCheck/HealthCheckOverviewDialog.resx
  XenModel/Messages.Designer.cs
  XenModel/Messages.resx
Labels: 2 approvals

#2864 CP-38073: Corrected resx file for the Chinese language.
  XenAdmin/Properties/Resources.zh-CN.resx
Labels: 2 approvals

#2863 Cherry picked CP-38073 from master and resolved conflicts
  XenAdmin/Images.cs
  XenAdmin/Images/rocky_16x.png
  XenAdmin/Properties/Resources.Designer.cs
  XenAdmin/Properties/Resources.ja.resx
  XenAdmin/Properties/Resources.resx
  XenAdmin/Properties/Resources.zh-CN.resx
  XenAdmin/Wizards/NewVMWizard/Page_Template.cs
  XenAdmin/XenAdmin.csproj
  XenModel/Icons.cs
  XenModel/Messages.Designer.cs
  XenModel/Messages.ja.resx
  XenModel/Messages.resx
  XenModel/Messages.zh-CN.resx
  XenModel/XenAPI-Extensions/VM.cs
  XenModel/XenSearch/Common.cs
Labels: 2 approvals
