Repository xenserver/xenadmin, pull requests merged in 2021-12, with the labels that each got.

#2842 CA-350411: Add conditional page control refresh in Import Wizard
  XenAdmin/Commands/ImPortCommand.cs
  XenAdmin/MainWindow.cs
  XenAdmin/Wizards/ImportWizard/ImageVMConfigPage.cs
  XenAdmin/Wizards/ImportWizard/ImportWizard.cs
  XenAdmin/Wizards/ImportWizard/NetworkPickerPage.cs
  XenAdmin/Wizards/ImportWizard/StoragePickerPage.cs
  XenModel/Mappings/VmMapping.cs
  XenOvfApi/OVF.cs
Labels: 2 approvals, updated

#2854 CA-339273: Add source server/pool info to descriptions of actions that move/copy/import resources
  XenAdmin/Core/ActionBaseExtensions.cs
  XenAdmin/Dialogs/VMDialogs/MoveVMDialog.cs
  XenModel/Actions/VDI/MigrateVirtualDiskAction.cs
  XenModel/Actions/VDI/MoveVirtualDiskAction.cs
  XenModel/Actions/VM/ImportVmAction.cs
  XenModel/Actions/VM/VMCloneAction.cs
  XenModel/Actions/VM/VMCopyAction.cs
  XenModel/Actions/VM/VMCrossPoolMigrateAction.cs
  XenModel/Actions/VM/VMMigrateAction.cs
  XenModel/Actions/VM/VMMoveAction.cs
  XenModel/Messages.Designer.cs
  XenModel/Messages.resx
Labels: 2 approvals, updated

#2904 CA-359712 & CA-359709: Add RBAC check to VM/template copy/clone and Server Status Report Wizard
  XenAdmin/Commands/Command.cs
  XenAdmin/Commands/CopyTemplateCommand.cs
  XenAdmin/Commands/CopyVMCommand.cs
  XenAdmin/Wizards/BugToolWizardFiles/BugToolWizard.cs
  XenAdmin/Wizards/CrossPoolMigrateWizard/CrossPoolMigrateWizard.cs
  XenAdmin/Wizards/DRWizards/DRFailoverWizard.cs
  XenAdmin/Wizards/ExportWizard/ExportApplianceWizard.cs
  XenAdmin/Wizards/GenericPages/RBACWarningPage.cs
  XenAdmin/Wizards/HAWizard.cs
  XenAdmin/Wizards/ImportWizard/ImportWizard.cs
  XenAdmin/Wizards/NewPolicyWizard/NewPolicyWizard.cs
  XenAdmin/Wizards/NewSRWizard.cs
  XenAdmin/Wizards/NewVMApplianceWizard/NewVMApplianceWizard.cs
  XenAdmin/Wizards/NewVMWizard/NewVMWizard.cs
  XenAdmin/XenAdmin.csproj
  XenModel/Actions/Host/SingleHostStatusAction.cs
  XenModel/Actions/SR/SrRefreshAction.cs
  XenModel/Actions/VM/VMCloneAction.cs
  XenModel/Actions/VM/VMCopyAction.cs
  XenModel/Messages.Designer.cs
  XenModel/Messages.resx
  XenModel/Utils/Helpers.cs
  XenModel/XenAPI-Extensions/VM.cs
Labels: 2 approvals, updated

#2912 CP-32667 Added download action to CHC
  XenAdmin/Alerts/Types/ClientUpdateAlert.cs
  XenAdmin/TabPages/ManageUpdatesPage.cs
Labels: 2 approvals

#2910 CP-38473: Block RPU if the pool has hosts with certificate key length less than 2048.
  XenAdmin/Diagnostics/Checks/CertificateKeyLengthCheck.cs
  XenAdmin/Diagnostics/Problems/HostProblem/CertificateKeyLengthProblem.cs
  XenAdmin/Diagnostics/Problems/HostProblem/PowerOniLoProblem.cs
  XenAdmin/Diagnostics/Problems/PoolProblem/HealthCheckServiceProblem.cs
  XenAdmin/Diagnostics/Problems/PoolProblem/LegacySslProblem.cs
  XenAdmin/Diagnostics/Problems/PoolProblem/NotLicensedForAutomatedUpdatesWarning.cs
  XenAdmin/Diagnostics/Problems/PoolProblem/VSwitchControllerProblem.cs
  XenAdmin/Diagnostics/Problems/Warning.cs
  XenAdmin/Wizards/RollingUpgradeWizard/RollingUpgradeWizardPrecheckPage.cs
  XenAdmin/XenAdmin.csproj
  XenModel/Messages.Designer.cs
  XenModel/Messages.resx
Labels: 2 approvals

#2905 CA-343229: Changing roles when logged in as an AD user only takes effect after logging out/in
  XenAdmin/Commands/DisconnectCommand.cs
  XenAdmin/TabPages/AdPage.cs
  XenAdmin/TabPages/AdPage.resx
  XenModel/Actions/AD/AddRemoveRolesAction.cs
  XenModel/Actions/AD/AddRemoveSubjectsAction.cs
  XenModel/Messages.Designer.cs
  XenModel/Messages.resx
Labels: 2 approvals

#2914 (Stockholm) CA-362018: Improve update notification dismissal message
  XenModel/Messages.Designer.cs
  XenModel/Messages.resx
Labels: 2 approvals

#2907 CP-36392: Misc fixes to flagged Bugs
  XenAdmin/Actions/GUIActions/ExternalPluginAction.cs
  XenAdmin/Commands/Controls/VMOperationToolStripMenuItem.cs
  XenAdmin/Controls/SnapshotTreeView.cs
  XenAdmin/Dialogs/GraphDetailsDialog.cs
  XenAdmin/MainWindow.cs
  XenAdmin/SettingsPanels/EditNetworkPage.cs
  XenAdmin/SettingsPanels/PerfmonAlertEditPage.cs
  XenAdmin/SettingsPanels/VMHAEditPage.cs
  XenAdmin/SettingsUpdate.cs
  XenAdmin/Wizards/BugToolWizardFiles/BugToolPageSelectCapabilities.cs
  XenAdmin/Wizards/BugToolWizardFiles/BugToolWizard.cs
  XenAdmin/Wizards/PatchingWizard/AutomatedUpdatesBasePage.cs
  XenAdmin/Wizards/PatchingWizard/PlanActions/RemoveUpdateFilesFromMaster.cs
  XenCenterLib/ChangeableList.cs
  XenModel/Actions/Host/ApplyLicenseEditionAction.cs
  XenModel/Actions/OvfActions/Import.cs
  XenModel/Actions/ProduceConsumerQueue.cs
  XenModel/Actions/VDI/DetachVirtualDiskAction.cs
  XenModel/Alerts/Types/Alert.cs
  XenModel/ServerDBs/FakeAPI/fakePool.cs
  XenModel/WLB/WlbOptimizationRecommendation.cs
  XenModel/WLB/WlbPoolConfiguration.cs
  XenModel/WLB/WlbScheduledTask.cs
  XenModel/XenAPI-Extensions/XenObject.cs
  XenModel/XenServerProxy/RbacCollectorProxy.cs
  XenOvfApi/OVF.cs
  XenOvfApi/Security.cs
  XenOvfApi/Utilities/ValueMaps.cs
Labels: 2 approvals, updated

#2917 CP-36392: Amend WLB tests to account for deleted property
  XenAdminTests/UnitTests/WlbTests/WlbPoolConfigurationTests.cs
Labels: 2 approvals

#2916 (master) CA-362018: Improve update notification dismissal message
  XenModel/Messages.Designer.cs
  XenModel/Messages.resx
Labels: 1 approval
