Repository xenserver/xenadmin, pull requests merged in 2022-02, with the labels that each got.

#2939 XSI-1177/CA-362931: A number of new version pre-checks did not run when in automated updates mode.
  XenAdmin/Diagnostics/Checks/PoolHasGFS2SR.cs
  XenAdmin/Wizards/PatchingWizard/PatchingWizard_PrecheckPage.cs
Labels: 2 approvals

#2942 CP-38526/XSI-1055: Improved import performance for OVF/OVA packages with .vhd disks.
  XenModel/Actions/OvfActions/Import.cs
Labels: 2 approvals

#2941 Some corrections and refactoring on the console panel
  XenAdmin/Commands/RevertToSnapshotCommand.cs
  XenAdmin/Commands/TakeSnapshotCommand.cs
  XenAdmin/ConsoleView/VNCTabView.cs
  XenAdmin/ConsoleView/VNCView.cs
  XenAdmin/Controls/ConsolePanel.cs
  XenAdmin/MainWindow.cs
Labels: 2 approvals

#2943 CP-39053: Bumped branding library version to v4.1.
  Jenkinsfile
Labels: 2 approvals

#2945 CP-39132 (UPD-816): Bumped branding library version to v2.5.
  Jenkinsfile
Labels: 2 approvals

#2935 CA-362709, CA-362711: Reworked the logic for allowing full disk copy …
  XenAdmin/Wizards/NewVMWizard/Page_Storage.Designer.cs
  XenAdmin/Wizards/NewVMWizard/Page_Storage.cs
  XenModel/Actions/VM/CreateVMAction.cs
  XenModel/Messages.Designer.cs
  XenModel/Messages.resx
Labels: 2 approvals, updated

#2947 CA-363610: OVF import: fixed upload of OS fixup ISO.
  XenModel/Actions/OvfActions/Import.cs
Labels: 2 approvals

#2949 CA-363819: Fixed issue where VM network usage data were not shown on the Search TabPage.
  XenModel/XenSearch/Common.cs
Labels: 2 approvals

#2948 CP-38832: Bumped branding library version to v4.2.
  Jenkinsfile
Labels: 2 approvals

#2951 XSI-1177/CA-362931: missing null check.
  XenAdmin/Wizards/PatchingWizard/PatchingWizard_PrecheckPage.cs
Labels: 2 approvals

#2953 Update alert test fixes
  XenAdminTests/ClassVerifiers.cs
  XenAdminTests/UnitTests/AlertTests/AlertClassUnitTestData.cs
  XenAdminTests/UnitTests/AlertTests/XenCenterUpdateAlertTests.cs
  XenModel/Actions/Updates/DownloadAndUpdateClientAction.cs
Labels: 1 approval, updated

#2954 CA-361078: Parse OVFs without a `Limit` element in the vCPUs section
  XenModel/Actions/OvfActions/Import.cs
Labels: 1 approval

#2955 Hide the client update button by default. Added null check.
  XenAdmin/MainWindow.cs
Labels: 2 approvals

#2958 L10N : Resx Sync
  XenAdmin/Dialogs/LegalNoticesDialog.ja.resx
  XenAdmin/Dialogs/LegalNoticesDialog.zh-CN.resx
  XenAdmin/Dialogs/OptionsDialog.ja.resx
  XenAdmin/Dialogs/OptionsDialog.zh-CN.resx
  XenAdmin/SettingsPanels/LivePatchingEditPage.ja.resx
  XenAdmin/TabPages/GeneralTabPage.ja.resx
  XenAdmin/TabPages/GeneralTabPage.zh-CN.resx
  XenAdmin/TabPages/HistoryPage.ja.resx
  XenAdmin/TabPages/HistoryPage.zh-CN.resx
Labels: 2 approvals
