Repository xenserver/xenadmin, pull requests merged in 2022-04, with the labels that each got.

#2982 CA-334613: Clip region within which performance graph lines are drawn
  XenAdmin/Controls/CustomDataGraph/LineRenderer.cs
Labels: 2 approvals

#2978 Compacted ParallelAction and MultipleAction constructors.
  XenAdmin/Core/HealthCheck.cs
  XenAdmin/Core/Updates.cs
  XenAdmin/Diagnostics/Problems/PoolProblem/MissingMultipleFCSRsProblem.cs
  XenAdmin/Dialogs/MoveVirtualDiskDialog.cs
  XenAdmin/Wizards/NewSRWizard.cs
  XenAdmin/Wizards/PatchingWizard/PatchingWizard_PrecheckPage.cs
  XenModel/Actions/MultipleAction.cs
  XenModel/Actions/MultipleActionLauncher.cs
  XenModel/Actions/ParallelAction.cs
Labels: 2 approvals

#2977 Some corrections on the DRWizard prechecks page:
  XenAdmin/Diagnostics/Checks/DR/AssertCanBeRecoveredCheck.cs
  XenAdmin/Diagnostics/Problems/PoolProblem/MissingSRProblem.cs
  XenAdmin/Wizards/DRWizards/DRFailoverWizardPrecheckPage.Designer.cs
  XenAdmin/Wizards/DRWizards/DRFailoverWizardPrecheckPage.cs
  XenAdmin/Wizards/DRWizards/DRFailoverWizardPrecheckPage.resx
  XenModel/Messages.Designer.cs
  XenModel/Messages.resx
Labels: 2 approvals

#2944 CP-38542: Remove option to disable live patching.
  XenAdmin/Dialogs/PropertiesDialog.cs
  XenAdmin/SettingsPanels/LivePatchingEditPage.Designer.cs
  XenAdmin/SettingsPanels/LivePatchingEditPage.cs
  XenAdmin/SettingsPanels/LivePatchingEditPage.ja.resx
  XenAdmin/SettingsPanels/LivePatchingEditPage.resx
  XenAdmin/SettingsPanels/LivePatchingEditPage.zh-CN.resx
  XenAdmin/XenAdmin.csproj
  XenModel/Messages.Designer.cs
  XenModel/Messages.resx
Labels: 2 approvals

#2984 CA-365905 (XSI-1215): Create a temporary file in the target download …
  XenModel/XenAPI/HTTP.cs
Labels: 1 approval

#2973 CP-39382: Lock msi file while verifying and launching install process
  XenAdmin/Alerts/Types/ClientUpdateAlert.cs
  XenModel/Actions/Updates/DownloadAndUpdateClientAction.cs
  XenModel/Messages.Designer.cs
  XenModel/Messages.resx
Labels: 2 approvals

#2988 CA-366115 & CA-366116: Quick Update Feature - FQP Bug fixes
  XenAdmin/Alerts/Types/ClientUpdateAlert.cs
  XenModel/Actions/Updates/DownloadAndUpdateClientAction.cs
Labels: 2 approvals

#2986 [CHC] CA-366069 & XSI-1222: Fix incorrect capitalisation of value in Japanese version + add some case insensitive checks
  CFUValidator/Validators/ZipContentsValidator.cs
  XenAdmin/Diagnostics/Hotfixing/SingleHotfix.cs
  XenAdmin/Wizards/PatchingWizard/PatchingWizard_SelectPatchPage.cs
  XenAdmin/Wizards/PatchingWizard/PlanActions/DownloadPatchPlanAction.cs
  XenAdmin/Wizards/WizardHelpers.cs
  XenModel/Actions/Updates/DownloadAndUnzipXenServerPatchAction.cs
  XenModel/InvisibleMessages.Designer.cs
  XenModel/InvisibleMessages.ja.resx
  XenModel/InvisibleMessages.resx
  XenModel/InvisibleMessages.zh-CN.resx
Labels: updated

#2983 Update maintainers list
  MAINTAINERS
Labels: 1 approval

#2987 [XC] CA-366069 & XSI-1222: Fix incorrect capitalisation of value in Japanese version + add some case insensitive checks
  CFUValidator/Validators/ZipContentsValidator.cs
  XenAdmin/Diagnostics/Hotfixing/SingleHotfix.cs
  XenAdmin/Wizards/PatchingWizard/PatchingWizard_SelectPatchPage.cs
  XenAdmin/Wizards/PatchingWizard/PlanActions/DownloadPatchPlanAction.cs
  XenAdmin/Wizards/WizardHelpers.cs
  XenModel/Actions/Updates/DownloadAndUnzipXenServerPatchAction.cs
  XenModel/InvisibleMessages.Designer.cs
  XenModel/InvisibleMessages.ja.resx
  XenModel/InvisibleMessages.resx
  XenModel/InvisibleMessages.zh-CN.resx
Labels: 1 approval, updated

#2990 CA-365905 (XSI-1215): Reworked previous solution:
  XenModel/XenAPI/HTTP.cs
Labels: 2 approvals

#2991 CP-39571: Removed spaces from the name of the log files.
  XenAdmin/app.config
  XenModel/Actions/StatusReportAction.cs
Labels: 2 approvals

#2996 Added code owners (default reviewers).
  .github/CODEOWNERS
Labels: 2 approvals

#2993 Port PRs #2984 and #2990 to master
  XenModel/XenAPI/HTTP.cs
Labels: 2 approvals

#2999 CP-39114: Rename `dev-CHCUpdates.xml` to `stage-test-CHCUpdates.xml`
  scripts/xenadmin-build.sh
Labels: 2 approvals
