Repository xenserver/xenadmin, pull requests merged in 2022-05, with the labels that each got.

#2997 CA-329538: Tell the user to ensure tools are installed if a VM cannot be migrated via drag-and-drop
  XenAdmin/Commands/DragDropCrossPoolMoveHaltedVMCommand.cs
  XenAdmin/Commands/DragDropMigrateVMCommand.cs
  XenAdmin/Controls/MainWindowControls/NavigationView.cs
  XenModel/Messages.Designer.cs
  XenModel/Messages.resx
Labels: 2 approvals, updated

#3001 CA-311156: Select the home node prior to starting restoring sessions
  XenAdmin/MainWindow.cs
Labels: 2 approvals

#3002 CP-39720: Enable auth tokens
  XenAdmin/Core/Registry.cs
  XenAdmin/WinformsXenAdminConfigProvider.cs
  XenModel/Actions/Updates/DownloadAndUpdateClientAction.cs
  XenModel/Actions/Updates/DownloadUpdatesXmlAction.cs
  XenModel/XenAdminConfigManager.cs
  XenServerHealthCheck/XenServerHealthCheckConfigProvider.cs
Labels: 1 approval, updated

#3004 Point URL in `CHCUpdates.xml` to MSI location
  scripts/xenadmin-build.sh
Labels: 1 approval

#3010 Fixed broken build and made some additional L10n corrections to the layout.
  XenAdmin/Wizards/DRWizards/DRFailoverWizardPrecheckPage.ja.resx
  XenAdmin/Wizards/DRWizards/DRFailoverWizardPrecheckPage.resx
  XenAdmin/Wizards/DRWizards/DRFailoverWizardPrecheckPage.zh-CN.resx
  XenAdmin/Wizards/DRWizards/DRFailoverWizardRecoverPage.ja.resx
  XenAdmin/Wizards/DRWizards/DRFailoverWizardRecoverPage.resx
  XenAdmin/Wizards/DRWizards/DRFailoverWizardRecoverPage.zh-CN.resx
Labels: 2 approvals

#3007 CP-36392: Fixes to sonarqube score.
  CommandLib/export.cs
  XenAdmin/VNC/VNCStream.cs
Labels: 2 approvals

#2998 CA-293683: Prevent automatic scrolling in RPU wizard if user has scrolled manually
  XenAdmin/Controls/SmartScrollTextBox.cs
  XenAdmin/Wizards/PatchingWizard/AutomatedUpdatesBasePage.cs
  XenAdmin/Wizards/PatchingWizard/AutomatedUpdatesBasePage.designer.cs
  XenAdmin/Wizards/PatchingWizard/AutomatedUpdatesBasePage.resx
  XenAdmin/Wizards/PatchingWizard/PatchingWizard_UploadPage.cs
  XenAdmin/Wizards/RollingUpgradeWizard/RollingUpgradeUpgradePage.cs
  XenAdmin/XenAdmin.csproj
  XenCenterLib/Win32.cs
Labels: 2 approvals

#3003 CA-294370: Rewrote logic calculating if migration is allowed + some other fixes.
  XenAdmin/Commands/CopyVMCommand.cs
  XenAdmin/Commands/CrossPoolCopyVMCommand.cs
  XenAdmin/Commands/CrossPoolMigrateCommand.cs
  XenAdmin/Commands/CrossPoolMoveVMCommand.cs
  XenAdmin/Commands/DragDropAddHostToPoolCommand.cs
  XenAdmin/Commands/DragDropCommand.cs
  XenAdmin/Commands/DragDropCrossPoolMoveHaltedVMCommand.cs
  XenAdmin/Commands/DragDropIntoFolderCommand.cs
  XenAdmin/Commands/DragDropMigrateVMCommand.cs
  XenAdmin/Commands/DragDropTagCommand.cs
  XenAdmin/Controls/MainWindowControls/NavigationView.cs
  XenAdmin/Wizards/CrossPoolMigrateWizard/CrossPoolMigrateDestinationPage.cs
  XenAdmin/Wizards/CrossPoolMigrateWizard/Filters/CrossPoolMigrateCanMigrateFilter.cs
  XenAdmin/Wizards/CrossPoolMigrateWizard/Filters/ResidentHostIsSameAsSelectionFilter.cs
  XenAdmin/Wizards/CrossPoolMigrateWizard/Filters/WlbEnabledFilter.cs
  XenAdmin/Wizards/GenericPages/DelayLoadingOptionComboBoxItem.cs
  XenAdmin/Wizards/GenericPages/ReasoningFilter.cs
  XenAdmin/Wizards/GenericPages/SelectMultipleVMDestinationPage.cs
  XenAdmin/Wizards/ImportWizard/HardwareCompatibilityFilter.cs
  XenAdmin/Wizards/ImportWizard/ImportSelectHostPage.cs
  XenAdmin/XenAdmin.csproj
  XenModel/Messages.Designer.cs
  XenModel/Messages.resx
Labels: 2 approvals

#3011 CA-366140: Reverted original solution. Handled error thrown when retrieving datasources.
  XenAdmin/Actions/GUIActions/SaveDataSourceStateAction.cs
  XenAdmin/Controls/CustomDataGraph/ArchiveMaintainer.cs
  XenModel/Actions/GetDataSourcesAction.cs
Labels: 2 approvals

#3014 Additional corrections to PRs #3006 and #3007
  CommandLib/export.cs
  xe/Logger.cs
Labels: 2 approvals
