Repository xenserver/xenadmin, pull requests merged in 2022-01, with the labels that each got.

#2913 CA-361078: vCPUs count isn't exported/imported within OVFs
  XenModel/Actions/OvfActions/Export.cs
  XenModel/Actions/OvfActions/Import.cs
  XenOvfApi/OVF.cs
Labels: 1 approval, updated

#2889 CA-359124 & CA-360426: Add snapshot VIFs to mapping during cross pool migration & fix VIF mapping in cross pool migration
  XenAdmin/Wizards/ConversionWizard/ConversionNetworkPage.cs
  XenAdmin/Wizards/CrossPoolMigrateWizard/CrossPoolMigrateNetworkingPage.cs
  XenAdmin/Wizards/CrossPoolMigrateWizard/CrossPoolMigrationNetworkResource.cs
  XenAdmin/Wizards/CrossPoolMigrateWizard/Filters/CrossPoolMigrateCanMigrateFilter.cs
  XenAdmin/Wizards/GenericPages/NetworkResource.cs
  XenAdmin/Wizards/GenericPages/SelectMultipleVMNetworkPage.cs
  XenAdmin/Wizards/ImportWizard/OvfNetworkResource.cs
  XenModel/Actions/VM/VMCrossPoolMigrateAction.cs
  XenModel/Mappings/VmMapping.cs
  XenModel/XenAPI-Extensions/Failure.cs
Labels: 2 approvals

#2915 CA-361926: Ensure `Messages.resx` in XenCenter stays alphabetically sorted
  .github/workflows/main.yml
  scripts/check_strings_sorting.ps1
  scripts/sort_strings.ps1
Labels: 2 approvals

#2920 L10N : Resx Sync and Translation Updates
  XenAdmin/Controls/AffinityPicker.zh-CN.resx
  XenAdmin/Controls/NetworkingTab/NetworkList.ja.resx
  XenAdmin/Controls/NetworkingTab/NetworkList.zh-CN.resx
  XenAdmin/Dialogs/ConfirmVMDeleteDialog.zh-CN.resx
  XenAdmin/Dialogs/DRConfigureDialog.ja.resx
  XenAdmin/Dialogs/DRConfigureDialog.zh-CN.resx
  XenAdmin/Dialogs/HealthCheck/HealthCheckOverviewDialog.ja.resx
  XenAdmin/Dialogs/HealthCheck/HealthCheckOverviewDialog.zh-CN.resx
  XenAdmin/Dialogs/OptionsPages/SaveAndRestoreOptionsPage.ja.resx
  XenAdmin/Dialogs/OptionsPages/UpdatesOptionsPage.ja.resx
  XenAdmin/Dialogs/OptionsPages/UpdatesOptionsPage.zh-CN.resx
  XenAdmin/Dialogs/VmSnapshotDialog.ja.resx
  XenAdmin/Dialogs/VmSnapshotDialog.zh-CN.resx
  XenAdmin/Dialogs/WarningDialogs/LVMoHBAWarningDialog.ja.resx
  XenAdmin/Help/HelpManager.ja.resx
  XenAdmin/Help/HelpManager.zh-CN.resx
  XenAdmin/MainWindow.ja.resx
  XenAdmin/MainWindow.zh-CN.resx
  XenAdmin/SettingsPanels/Wlb/WlbAdvancedSettingsPage.zh-CN.resx
  XenAdmin/SettingsPanels/Wlb/WlbMetricWeightingPage.zh-CN.resx
  XenAdmin/Wizards/DRWizards/DRFailoverWizardWelcomePage.zh-CN.resx
  XenAdmin/Wizards/ExportWizard/ExportOptionsPage.ja.resx
  XenAdmin/Wizards/ExportWizard/ExportOptionsPage.zh-CN.resx
  XenAdmin/Wizards/NewNetworkWizard_Pages/NetWChinDetails.zh-CN.resx
  XenAdmin/Wizards/NewPolicyWizard/NewPolicySnapshotTypePage.zh-CN.resx
  XenAdmin/Wizards/PatchingWizard/PatchingWizard_FirstPage.ja.resx
  XenAdmin/Wizards/PatchingWizard/PatchingWizard_FirstPage.zh-CN.resx
  XenModel/InvisibleMessages.ja.resx
  XenModel/InvisibleMessages.zh-CN.resx
  XenModel/Messages.ja.resx
  XenModel/Messages.zh-CN.resx
  XenModel/XenAPI/FriendlyErrorNames.ja.resx
  XenModel/XenAPI/FriendlyErrorNames.zh-CN.resx
Labels: 2 approvals

#2924 Revert "Sort .resx strings"
  Branding/Branding.resx
  XenModel/FriendlyNames.ja.resx
  XenModel/FriendlyNames.resx
  XenModel/FriendlyNames.zh-CN.resx
  XenModel/InvisibleMessages.ja.resx
  XenModel/InvisibleMessages.resx
  XenModel/InvisibleMessages.zh-CN.resx
  XenModel/Messages.ja.resx
  XenModel/Messages.resx
  XenModel/Messages.zh-CN.resx
  XenModel/UnitStrings.ja.resx
  XenModel/UnitStrings.resx
  XenModel/UnitStrings.zh-CN.resx
  XenOvfApi/Content.ja.resx
  XenOvfApi/Content.resx
  XenOvfApi/Content.zh-CN.resx
  XenOvfApi/Messages.ja.resx
  XenOvfApi/Messages.resx
  XenOvfApi/Messages.zh-CN.resx
Labels: 2 approvals

#2923 L10N : Translation Update
  XenModel/Messages.ja.resx
  XenModel/Messages.zh-CN.resx
Labels: 1 approval

#2925 Retry sorting .resx strings.
  Branding/Branding.resx
  XenModel/FriendlyNames.ja.resx
  XenModel/FriendlyNames.resx
  XenModel/FriendlyNames.zh-CN.resx
  XenModel/InvisibleMessages.ja.resx
  XenModel/InvisibleMessages.resx
  XenModel/InvisibleMessages.zh-CN.resx
  XenModel/Messages.ja.resx
  XenModel/Messages.resx
  XenModel/Messages.zh-CN.resx
  XenModel/UnitStrings.ja.resx
  XenModel/UnitStrings.resx
  XenModel/UnitStrings.zh-CN.resx
  XenOvfApi/Content.ja.resx
  XenOvfApi/Content.resx
  XenOvfApi/Content.zh-CN.resx
  XenOvfApi/Messages.ja.resx
  XenOvfApi/Messages.resx
  XenOvfApi/Messages.zh-CN.resx
Labels: 2 approvals

#2926 CA-362352, CA-362355, CA-362354 & CA-362353: Fix misc issues with PuTTY removal
  XenAdmin/ConsoleView/VNCTabView.cs
  XenAdmin/Dialogs/OptionsPages/ExternalToolsOptionsPage.Designer.cs
  XenAdmin/Dialogs/OptionsPages/ExternalToolsOptionsPage.cs
  XenAdmin/Program.cs
  XenAdmin/Settings.cs
  XenModel/Messages.Designer.cs
  XenModel/Messages.resx
Labels: 2 approvals

#2934 CP-38483: Unbundle putty from Citrix Hypervisor Center
  WixInstaller/XenCenter.wxs
  XenAdmin/ConsoleView/VNCTabView.cs
  XenAdmin/ConsoleView/VNCTabView.resx
  XenAdmin/Dialogs/LegalNoticesDialog.resx
  XenAdmin/Dialogs/OptionsDialog.Designer.cs
  XenAdmin/Dialogs/OptionsDialog.cs
  XenAdmin/Dialogs/OptionsDialog.resx
  XenAdmin/Dialogs/OptionsPages/ExternalToolsOptionsPage.Designer.cs
  XenAdmin/Dialogs/OptionsPages/ExternalToolsOptionsPage.cs
  XenAdmin/Dialogs/OptionsPages/ExternalToolsOptionsPage.ja.resx
  XenAdmin/Dialogs/OptionsPages/ExternalToolsOptionsPage.resx
  XenAdmin/Dialogs/OptionsPages/ExternalToolsOptionsPage.zh-CN.resx
  XenAdmin/MainWindow.Designer.cs
  XenAdmin/MainWindow.cs
  XenAdmin/Program.cs
  XenAdmin/Properties/Settings.Designer.cs
  XenAdmin/Properties/Settings.settings
  XenAdmin/Settings.cs
  XenAdmin/TabPages/GeneralTabPage.Designer.cs
  XenAdmin/TabPages/GeneralTabPage.cs
  XenAdmin/TabPages/GeneralTabPage.resx
  XenAdmin/XenAdmin.csproj
  XenAdmin/app.config
  XenModel/Messages.Designer.cs
  XenModel/Messages.resx
  XenModel/SshConsole.cs
  XenModel/XenModel.csproj
  packages/DOTNET_BUILD_LOCATION
  scripts/deps-map.json
  scripts/download_packages.ps1
  scripts/xenadmin-build.sh
Labels: 2 approvals, blocked

#2928 CP-37850: Update RPU005 to version 4.0
  XenAdmin/Commands/CertificateCommand.cs
  XenAdmin/Commands/EnableTlsVerificationCommand.cs
  XenAdmin/Commands/InstallNewUpdateCommand.cs
  XenAdmin/Diagnostics/Checks/CertificateKeyLengthCheck.cs
  XenAdmin/Diagnostics/Checks/HealthCheckServiceCheck.cs
  XenAdmin/Diagnostics/Checks/SafeToUpgradeCheck.cs
  XenAdmin/Diagnostics/Hotfixing/HotfixFactory.cs
  XenAdmin/MainWindow.cs
  XenAdmin/TabPages/GeneralTabPage.cs
  XenAdmin/TabPages/ManageUpdatesPage.cs
  XenAdmin/Wizards/PatchingWizard/PatchingWizard_FirstPage.cs
  XenAdmin/Wizards/PatchingWizard/PatchingWizard_SelectServers.cs
  XenModel/Utils/Helpers.cs
  scripts/hotfix-map.json
Labels: 2 approvals, blocked

#2930 CA-261979: Use utf-8 encoding for logging…
  XenAdmin/app.config
  XenServerHealthCheck/app.config
Labels: 2 approvals, blocked

#2927 CP-38832: Bump `xencenter-pipeline` to v4.3
  Jenkinsfile
Labels: 2 approvals, blocked

#2931 Minor refactoring; null check; tidy up
  XenAdmin/Program.cs
  XenAdmin/Settings.cs
  XenAdmin/SettingsUpdate.cs
  XenAdmin/XenAdmin.csproj
Labels: 2 approvals
