Repository xenserver/xenadmin, pull requests merged in 2023-08, with the labels that each got.

#3186 CA-380718: Ensure language code is passed when running `PerfmonOptionsDefinitionAction`
  XenAdmin/SettingsPanels/PerfmonAlertOptionsPage.cs
Labels: 2 approvals, ITE

#3191 CA-381017: Pass `OriginalString` when fetching EUA
  XenAdmin/Diagnostics/Checks/UpgradeRequiresEUA.cs
  XenModel/Utils/Helpers.cs
Labels: 2 approvals, ITE, ASAP

#3194 Master->feature/cdn-updates
  XenAdmin/Diagnostics/Checks/UpgradeRequiresEUA.cs
  XenAdmin/Diagnostics/Problems/PoolProblem/PoolHasFCoESrWarning.cs
  XenAdmin/Dialogs/LicenseManager/LicenseManager.cs
  XenAdmin/Dialogs/LicenseManager/LicenseManager.resx
  XenAdmin/Dialogs/LicenseManager/LicenseManagerController.cs
  XenAdmin/MainWindow.cs
  XenAdmin/SettingsPanels/PerfmonAlertOptionsPage.cs
  XenAdmin/TabPages/GeneralTabPage.cs
  XenAdmin/TabPages/ManageUpdatesPage.cs
  XenAdmin/Wizards/NewSRWizard_Pages/ChooseSrTypePage.cs
  XenModel/InvisibleMessages.Designer.cs
  XenModel/InvisibleMessages.ja.resx
  XenModel/InvisibleMessages.resx
  XenModel/InvisibleMessages.zh-CN.resx
  XenModel/Messages.Designer.cs
  XenModel/Messages.resx
  XenModel/Utils/Helpers.cs
Labels: 2 approvals

#3201 CA-381593: Remove CIS privacy policy link from Server Status Report
  XenAdmin/Wizards/BugToolWizard/BugToolPageSelectCapabilities.Designer.cs
  XenAdmin/Wizards/BugToolWizard/BugToolPageSelectCapabilities.cs
  XenAdmin/Wizards/BugToolWizard/BugToolPageSelectCapabilities.resx
  XenModel/InvisibleMessages.Designer.cs
  XenModel/InvisibleMessages.resx
Labels: 2 approvals, ASAP

#3199 CA-381500: Fix `misc` instances of Unlicensed wording showing for post Nile host/pools
  XenAdmin/MainWindow.cs
  XenAdmin/TabPages/GeneralTabLicenseStatusStringifier.cs
  XenAdmin/TabPages/GeneralTabPage.cs
Labels: 2 approvals, ASAP

#3203 CA-381678: Fix misc wording issues in `ManageCdnUpdatesPage` export file
  XenAdmin/TabPages/ManageCdnUpdatesPage.cs
Labels: 2 approvals

#3200 CA-381502: Show the disabled reason in a new column. Extended the messages shown.
  XenAdmin/Dialogs/OptionsPages/UpdatesOptionsPage.Designer.cs
  XenAdmin/Dialogs/OptionsPages/UpdatesOptionsPage.cs
  XenAdmin/Dialogs/OptionsPages/UpdatesOptionsPage.resx
  XenAdmin/Wizards/PatchingWizard/PatchingWizard_SelectServers.Designer.cs
  XenAdmin/Wizards/PatchingWizard/PatchingWizard_SelectServers.cs
  XenAdmin/Wizards/PatchingWizard/PatchingWizard_SelectServers.resx
  XenModel/Messages.Designer.cs
  XenModel/Messages.resx
Labels: 2 approvals, ASAP

#3202 Wording change; corrections for supp-pack installation.
  XenAdmin/Diagnostics/Checks/HostNeedsRebootCheck.cs
  XenAdmin/TabPages/GeneralTabPage.cs
  XenAdmin/Wizards/PatchingWizard/PatchingWizard_ModePage.cs
  XenAdmin/Wizards/PatchingWizard/PatchingWizard_PrecheckPage.cs
  XenModel/Messages.Designer.cs
  XenModel/Messages.resx
Labels: 2 approvals, ASAP

#3198 UX improvements: CA-381442, XSI-1476, CA-375740
  XenAdmin/Alerts/Types/OutOfSyncWithCdnAlert.cs
  XenAdmin/Dialogs/PropertiesDialog.cs
  XenAdmin/Dialogs/ServerUpdates/ConfigCdnUpdatesPage.cs
  XenAdmin/Images.cs
  XenAdmin/Images/rpm_package.png
  XenAdmin/Properties/Resources.Designer.cs
  XenAdmin/Properties/Resources.resx
  XenAdmin/SettingsPanels/CustomFieldsDisplayPage.cs
  XenAdmin/TabPages/CdnUpdates/CdnExpandableRow.cs
  XenAdmin/Wizards/PatchingWizard/PatchingWizard_ModePage.Designer.cs
  XenAdmin/Wizards/PatchingWizard/PatchingWizard_ModePage.cs
  XenAdmin/XenAdmin.csproj
  XenModel/Messages.Designer.cs
  XenModel/Messages.resx
Labels: 2 approvals, ASAP

#3204 CA-381212, CA-381664, CA-381215, CP-44618
  Jenkinsfile
  XenAdmin/Core/Updates.cs
  XenAdmin/Wizards/HAWizard_Pages/Intro.resx
  XenModel/Actions/Updates/ApplyUpdatesFromCdnAction.cs
  XenModel/Actions/Updates/CheckForCdnUpdatesAction.cs
Labels: 2 approvals, ASAP

#3205 More fixes including CA-381728, CA-381618, CA-381225
  Branding/branding.sh
  XenAdmin/Alerts/Types/OutOfSyncWithCdnAlert.cs
  XenAdmin/Controls/ComboBoxes/VgpuComboBox.cs
  XenAdmin/Controls/XenTabPage.cs
  XenAdmin/Diagnostics/Checks/HaWlbOffCheck.cs
  XenAdmin/Dialogs/ServerUpdates/ConfigUpdatesDialog.cs
  XenAdmin/Help/HelpManager.resx
  XenAdmin/Help/extract-help-numbers
  XenAdmin/Help/extract-help-numbers-csv
  XenAdmin/MainWindow.cs
  XenAdmin/SettingsPanels/GpuEditPage.cs
  XenAdmin/TabPages/CdnUpdates/CdnExpandableRow.cs
  XenAdmin/TabPages/HAPage.cs
  XenAdmin/TabPages/ManageCdnUpdatesPage.cs
  XenAdmin/TabPages/ManageUpdatesPage.cs
  XenAdmin/Wizards/PatchingWizard/PatchingWizard.cs
  XenAdmin/Wizards/PatchingWizard/PatchingWizard_AutomatedUpdatesPage.cs
  XenAdmin/Wizards/PatchingWizard/PatchingWizard_FirstPage.cs
  XenAdmin/Wizards/PatchingWizard/PatchingWizard_ModePage.cs
  XenAdmin/Wizards/PatchingWizard/PatchingWizard_PatchingPage.cs
  XenAdmin/Wizards/PatchingWizard/PatchingWizard_PrecheckPage.cs
  XenAdmin/Wizards/PatchingWizard/PatchingWizard_SelectPatchPage.cs
  XenAdmin/Wizards/PatchingWizard/PatchingWizard_SelectServers.cs
  XenAdmin/Wizards/PatchingWizard/PatchingWizard_UploadPage.cs
  XenAdmin/Wizards/PatchingWizard/PlanActions/ApplyCdnUpdatesPlanAction.cs
  XenAdmin/Wizards/PatchingWizard/PlanActions/BringBabiesBackAction.cs
  XenAdmin/Wizards/PatchingWizard/PlanActions/EvacuateHostPlanAction.cs
  XenAdmin/Wizards/PatchingWizard/PlanActions/HostPlanAction.cs
  XenAdmin/Wizards/RollingUpgradeWizard/RollingUpgradeWizardPrecheckPage.cs
  XenAdmin/XenAdmin.csproj
  XenModel/Messages.Designer.cs
  XenModel/Messages.resx
  XenModel/XenAPI-Extensions/PIF.cs
  scripts/xenadmin-build.sh
Labels: 2 approvals, ASAP

#3206 CA-381212 : The protocol is not always HTTP/1.1
  XenModel/Actions/Updates/CheckForCdnUpdatesAction.cs
Labels: 2 approvals

#3207 CA-381212 : The error is not always Internal Server Error;
  XenModel/Actions/Updates/CheckForCdnUpdatesAction.cs
Labels: 2 approvals, ASAP

#3208 (master) CA-381212 : The error is not always Internal Server Error
  XenModel/Actions/Updates/CheckForCdnUpdatesAction.cs
Labels: 2 approvals, ITE

#3216 Stop building this branch (release/2022/d).
  Jenkinsfile.EOL
Labels: 2 approvals

#3215 Stop building this branch (release/2022/c).
  Jenkinsfile.EOL
Labels: 2 approvals

#3214 Stop building this branch (release/2022/b).
  Jenkinsfile.EOL
Labels: 2 approvals

#3213 Stop building this branch (release/2022/a).
  Jenkinsfile.EOL
Labels: 2 approvals
