Repository xenserver/xenadmin, pull requests merged in 2023-07, with the labels that each got.

#3162 CA-377017: Improved message shown when attempting to export VMs with vTPMs as OVF/OVA packages.
  XenModel/Messages.Designer.cs
  XenModel/Messages.resx
Labels: 2 approvals

#3167 CA-379402: Fix EUA check & add hotfix check to `HostMemoryPostUpgradeCheck`
  XenAdmin/Diagnostics/Checks/HostMemoryPostUpgradeCheck.cs
  XenAdmin/Diagnostics/Checks/UpgradeRequiresEUA.cs
  XenAdmin/Wizards/RollingUpgradeWizard/RollingUpgradeWizardPrecheckPage.cs
Labels: 1 approval, updated, ASAP

#3136 CA-376480, CA-374325, & CA-378489: Prevent two instances from starting after running installer; Add desktop shortcut option; Remove existing shortcuts
  WixInstaller/XenCenter.wxs
  WixInstaller/wix_src.patch
Labels: 1 approval, updated

#3160 Miscellaneous fixes to vCPUs warnings
  XenAdmin/Wizards/GenericPages/SelectMultipleVMDestinationPage.cs
  XenAdmin/Wizards/ImportWizard/ImportSelectHostPage.cs
  XenModel/Messages.Designer.cs
  XenModel/Messages.resx
Labels: 1 approval, updated, ASAP

#3166 CP-43770: Removed images from the WLB credentials dialog (plus some refactoring and layout tweaks)
  Branding/Images/LeftArrow.png
  Branding/Images/RightArrow.png
  Branding/Images/WLB.png
  Branding/Images/XS.png
  XenAdmin/Dialogs/Wlb/WlbCredentialsDialog.Designer.cs
  XenAdmin/Dialogs/Wlb/WlbCredentialsDialog.cs
  XenAdmin/Dialogs/Wlb/WlbCredentialsDialog.resx
  XenAdmin/Images.cs
  XenAdmin/Properties/Resources.Designer.cs
  XenAdmin/Properties/Resources.ja.resx
  XenAdmin/Properties/Resources.resx
  XenAdmin/Properties/Resources.zh-CN.resx
  XenAdmin/XenAdmin.csproj
Labels: 2 approvals

#3170 Disallow connection to havana servers.
  XenAdmin/Dialogs/AssignLicenseDialog.cs
  XenAdmin/MainWindow.cs
  XenModel/Utils/Helpers.Versions.cs
Labels: 2 approvals, ASAP

#3172 Corrections following the merge from master.
  XenAdmin/Diagnostics/Checks/CfuAvailabilityCheck.cs
  XenAdmin/Diagnostics/Checks/UpgradeRequiresEUA.cs
Labels: 2 approvals

#3174 Bumped branding to v4.17.
  Jenkinsfile
Labels: 1 approval, 2 approvals

#3165 CA-378758: Ensure all hosts in pool hit `HOST_NOT_ENOUGH_FREE_MEMORY` before preventing migration
  XenAdmin/Wizards/CrossPoolMigrateWizard/Filters/CrossPoolMigrateCanMigrateFilter.cs
Labels: 2 approvals

#3177 CA-380218: It was not possible to create VMs with VDIs smaller than the max disk…
  XenModel/XenAPI-Extensions/SR.cs
Labels: 2 approvals

#3181 Allow using test locations for downloading LCM hotfixes.
  XenModel/Actions/Updates/DownloadUnzipUpdateAction.cs
  XenModel/InvisibleMessages.Designer.cs
  XenModel/InvisibleMessages.resx
Labels: 1 approval, ITE

#3183 Bumped pipeline to v4.9
  Jenkinsfile
Labels: 1 approval

#3180 CA-380355 & CA-380545: Fix creation of Desktop shortcut in installer
  WixInstaller/XenCenter.wxs
  WixInstaller/wix_src.patch
Labels: 1 approval, updated, ASAP

#3164 CP-43070 adds leaf coalesce alert
  XenAdmin/Alerts/Types/LeafCoalesceAlert.cs
  XenAdmin/Alerts/Types/MessageAlert.cs
  XenAdmin/XenAdmin.csproj
  XenModel/Messages.Designer.cs
  XenModel/Messages.resx
  XenModel/XenAPI-Extensions/Message.cs
  XenModel/XenAPI/Message2.cs
Labels: 1 approval, updated, ASAP

#3163 CP-43000: Add edition and CSS upsell messages
  XenAdmin/Alerts/Types/MessageAlert.cs
  XenAdmin/Controls/CheckableDataGridView/CheckableDataGridViewRow.cs
  XenAdmin/Controls/PDSection.Designer.cs
  XenAdmin/Controls/PDSection.cs
  XenAdmin/Controls/PDSection.resx
  XenAdmin/Controls/SummaryPanel/ISummaryPanelView.cs
  XenAdmin/Controls/SummaryPanel/SummaryPanel.Designer.cs
  XenAdmin/Controls/SummaryPanel/SummaryPanel.cs
  XenAdmin/Controls/SummaryPanel/SummaryPanel.resx
  XenAdmin/Controls/SummaryPanel/SummaryPanelController.cs
  XenAdmin/Diagnostics/Problems/HostProblem/LicenseRestrictionProblem.cs
  XenAdmin/Dialogs/LicenseManager/ILicenseManagerView.cs
  XenAdmin/Dialogs/LicenseManager/LicenseCheckableDataGridView/LicenseCheckableDataGridView.cs
  XenAdmin/Dialogs/LicenseManager/LicenseDataGridViewRow.cs
  XenAdmin/Dialogs/LicenseManager/LicenseManager.Designer.cs
  XenAdmin/Dialogs/LicenseManager/LicenseManager.cs
  XenAdmin/Dialogs/LicenseManager/LicenseManager.resx
  XenAdmin/Dialogs/LicenseManager/LicenseManagerController.cs
  XenAdmin/Dialogs/LicenseManager/LicenseStatus.cs
  XenAdmin/Dialogs/NewPoolDialog.cs
  XenAdmin/Images.cs
  XenAdmin/Images/000_Tick_yellow_h32bit_16.png
  XenAdmin/Properties/Resources.Designer.cs
  XenAdmin/Properties/Resources.resx
  XenAdmin/TabPages/GeneralTabPage.cs
  XenAdmin/TabPages/ManageUpdatesPage.cs
  XenAdmin/TabPages/WlbPage.cs
  XenAdmin/XenAdmin.csproj
  XenModel/FriendlyNames.Designer.cs
  XenModel/FriendlyNames.resx
  XenModel/InvisibleMessages.Designer.cs
  XenModel/InvisibleMessages.ja.resx
  XenModel/InvisibleMessages.resx
  XenModel/InvisibleMessages.zh-CN.resx
  XenModel/Messages.Designer.cs
  XenModel/Messages.resx
  XenModel/PoolJoinRules.cs
  XenModel/Utils/Util.cs
  XenModel/XenAPI-Extensions/Host.cs
Labels: 1 approval, updated, ASAP
