Repository xenserver/xenadmin, pull requests merged in 2023-11, with the labels that each got.

#3250 Merge full 64 vCPUs support
  XenAdmin/Commands/ActivateVBDCommand.cs
  XenAdmin/Commands/DeactivateVBDCommand.cs
  XenAdmin/Commands/InstallToolsCommand.cs
  XenAdmin/Commands/VMLifeCycleCommand.cs
  XenAdmin/Controls/Ballooning/VMMemoryControlsBasic.cs
  XenAdmin/Controls/Ballooning/VMMemoryControlsNoEdit.cs
  XenAdmin/Controls/HaNtolControl.cs
  XenAdmin/Controls/NetworkingTab/NetworkList.cs
  XenAdmin/Controls/XenSearch/GroupingControl.cs
  XenAdmin/Controls/XenSearch/QueryElement.cs
  XenAdmin/Diagnostics/Checks/AssertCanEvacuateCheck.cs
  XenAdmin/Dialogs/EvacuateHostDialog.cs
  XenAdmin/Dialogs/VmSnapshotDialog.cs
  XenAdmin/SettingsPanels/EditNetworkPage.cs
  XenAdmin/SettingsPanels/GpuEditPage.cs
  XenAdmin/SettingsPanels/USBEditPage.cs
  XenAdmin/SettingsPanels/VMHAEditPage.cs
  XenAdmin/TabPages/GeneralTabPage.cs
  XenAdmin/Wizards/HAWizard.cs
  XenAdmin/Wizards/HAWizard_Pages/AssignPriorities.cs
  XenAdmin/XenSearch/Columns.cs
  XenAdminTests/SearchTests/VirtualisationStatePropertyQueryTests.cs
  XenModel/Actions/OvfActions/Export.cs
  XenModel/Actions/Pool/EnableHAAction.cs
  XenModel/Actions/VM/HAUnprotectVMAction.cs
  XenModel/Actions/VM/InstallPVToolsAction.cs
  XenModel/Actions/VM/SetHaPrioritiesAction.cs
  XenModel/Utils/Helpers.cs
  XenModel/XenAPI-Extensions/VM.cs
  XenModel/XenSearch/Common.cs
  XenModel/XenSearch/Search.cs
Labels: 2 approvals, ASAP

#3247 CA-384333: Update IPv4 regex and remove redundant codes.
  XenAdmin/SettingsPanels/NRPEEditPage.cs
Labels: 2 approvals, ASAP

#3246 CP-40844: Bumped pipeline version to v4.11.
  Jenkinsfile
Labels: 2 approvals, ASAP

#3249 CA-384579: Call previous NRPE plugin xapi to resolve certs permission issue
  XenModel/Actions/NRPE/NRPEHostConfiguration.cs
  XenModel/Actions/NRPE/NRPEUpdateAction.cs
Labels: 1 approval, ASAP

#3251 CA-384629: NRPE threshold check label mistake
  XenModel/Messages.Designer.cs
  XenModel/Messages.resx
Labels: 2 approvals, ASAP

#3255 Merge branch feature/nrpe to master
  XenAdmin/Dialogs/GraphDetailsDialog.Designer.cs
  XenAdmin/Dialogs/PropertiesDialog.cs
  XenAdmin/SettingsPanels/NRPEEditPage.CheckGroup.cs
  XenAdmin/SettingsPanels/NRPEEditPage.Designer.cs
  XenAdmin/SettingsPanels/NRPEEditPage.cs
  XenAdmin/SettingsPanels/NRPEEditPage.resx
  XenAdmin/XenAdmin.csproj
  XenModel/Actions/NRPE/NRPEHostConfiguration.cs
  XenModel/Actions/NRPE/NRPERetrieveAction.cs
  XenModel/Actions/NRPE/NRPEUpdateAction.cs
  XenModel/FriendlyNames.Designer.cs
  XenModel/FriendlyNames.resx
  XenModel/Messages.Designer.cs
  XenModel/Messages.resx
  XenModel/Utils/Helpers.Versions.cs
  XenModel/Utils/Helpers.cs
  XenModel/XenModel.csproj
Labels: 2 approvals

#3241 CA-383483: Rewrote the migration logic to fix regression
  XenAdmin/Commands/CrossPoolMigrateCommand.cs
  XenAdmin/Commands/VMOperationHostCommand.cs
  XenAdmin/Wizards/CrossPoolMigrateWizard/CrossPoolMigrateDestinationPage.cs
  XenAdmin/Wizards/CrossPoolMigrateWizard/Filters/CrossPoolMigrateFilter.cs
  XenAdmin/XenAdmin.csproj
Labels: 2 approvals, ASAP

#3258 CP-46393: Bumped branding library to v5.4. Small branding issue.
  Jenkinsfile
  XenModel/Messages.Designer.cs
  XenModel/Messages.resx
Labels: 2 approvals

#3248 CP-43651, one inconsistency, layout tweaks, and minor refactoring on MultipleDvdIsoList.
  XenAdmin/ConsoleView/VNCTabView.Designer.cs
  XenAdmin/ConsoleView/VNCTabView.cs
  XenAdmin/ConsoleView/VNCTabView.resx
  XenAdmin/Controls/ComboBoxes/ISODropDownBox.cs
  XenAdmin/Controls/MultipleDvdIsoList.Designer.cs
  XenAdmin/Controls/MultipleDvdIsoList.cs
  XenAdmin/Controls/MultipleDvdIsoList.resx
  XenModel/Actions/VBD/VbdCreateAndPlugAction.cs
  XenModel/Messages.Designer.cs
  XenModel/Messages.resx
Labels: 2 approvals

#3259 CA-385151 & CP-45516: Fix skipped patch + Bump pipeline to v4.12
  Jenkinsfile
  WixInstaller/wix_src.patch
Labels: 2 approvals, ASAP
