Repository xenserver/xenadmin, pull requests merged in 2023-03, with the labels that each got.

#3111 [master] Update `CODEOWNERS` and `MAINTAINERS`
  .github/CODEOWNERS
  MAINTAINERS
Labels: 2 approvals

#3110 [stockholm] Update `CODEOWNERS` and `MAINTAINERS`
  .github/CODEOWNERS
  MAINTAINERS
Labels: 2 approvals

#3112 Reordered templates on the NewVM wizard:
  XenAdmin/Wizards/NewVMWizard/Page_Template.cs
  XenModel/XenAPI-Extensions/VM.cs
Labels: 2 approvals

#3086 CP-41737: Add FCoE deprecation warnings
  XenAdmin/Diagnostics/Checks/PoolHasDeprecatedSrsCheck.cs
  XenAdmin/Diagnostics/Problems/PoolProblem/PoolHasFCoESrWarning.cs
  XenAdmin/Diagnostics/Problems/Problem.cs
  XenAdmin/Diagnostics/Problems/Warning.cs
  XenAdmin/TabPages/GeneralTabPage.cs
  XenAdmin/Wizards/NewSRWizard_Pages/ChooseSrTypePage.cs
  XenAdmin/Wizards/RollingUpgradeWizard/RollingUpgradeWizardPrecheckPage.cs
  XenAdmin/XenAdmin.csproj
  XenModel/InvisibleMessages.Designer.cs
  XenModel/InvisibleMessages.resx
  XenModel/Messages.Designer.cs
  XenModel/Messages.resx
  XenModel/Utils/Helpers.Versions.cs
Labels: 2 approvals

#3108 CP-41775: Fix using Hanja/Hangeul keys over VNC
  XenAdmin/VNC/KeyMap.cs
Labels: 2 approvals

#3107 CA-375668: Report bytes uncompressed instead of percentage when uncompressing a gzip.
  XenAdmin/Wizards/ImportWizard/ImportSourcePage.cs
  XenModel/Messages.Designer.cs
  XenModel/Messages.resx
Labels: 2 approvals

#3113 CA-375703: Remove leftover language mentions in `XenCenter.wxs`
  WixInstaller/XenCenter.wxs
  scripts/xenadmin-build.sh
Labels: 2 approvals

#3117 (release/2023/a) CA-375942: Corrected RBAC check for create/destroy vTPM
  XenAdmin/Dialogs/VtmpManagementDialog.cs
  XenModel/Messages.Designer.cs
  XenModel/Messages.resx
Labels: 2 approvals

#3118 (master) CA-375942: Corrected RBAC check for create/destroy vTPM
  XenAdmin/Dialogs/VtmpManagementDialog.cs
  XenModel/Messages.Designer.cs
  XenModel/Messages.resx
Labels: 2 approvals

#3115 [master] CA-375556: Pass non-compressed file stream to `HTTP.CopyStream`
  XenModel/Actions/OvfActions/Import.cs
Labels: updated

#3116 [LCM] CA-375556: Pass non-compressed file stream to `HTTP.CopyStream`
  XenModel/Actions/OvfActions/Import.cs
Labels: 1 approval, updated

#3121 CP-42286: Add friendly name for `pool_total_session_count`
  XenAdmin/Controls/CustomDataGraph/DataSet.cs
  XenModel/FriendlyNames.Designer.cs
  XenModel/FriendlyNames.resx
Labels: 2 approvals

#3120 Dead/obsolete code removal and some issues on the AddServerDialog
  CREDITS.md
  WixInstaller/branding.wxi
  WixInstaller/branding.wxs
  XenAdmin/Dialogs/AddServerDialog.Designer.cs
  XenAdmin/Dialogs/AddServerDialog.cs
  XenAdmin/Dialogs/AddServerDialog.ja.resx
  XenAdmin/Dialogs/AddServerDialog.resx
  XenAdmin/Dialogs/AddServerDialog.zh-CN.resx
  XenAdmin/Dialogs/NewPoolDialog.cs
  XenAdmin/Dialogs/Wlb/WlbCredentialsDialog.cs
  XenAdmin/Network/AddServerTask.cs
  XenAdmin/Program.cs
  XenAdmin/Properties/Settings.Designer.cs
  XenAdmin/Properties/Settings.settings
  XenAdmin/Settings.cs
  XenAdmin/TestResources/TestResource.cs
  XenAdmin/TestResources/credits.xml
  XenAdmin/TestResources/interesting-development.xml
  XenAdmin/TestResources/interesting-production.xml
  XenAdmin/TestResources/interesting-xenapp.xml
  XenAdmin/XenAdmin.csproj
  XenCenterLib/StringUtility.cs
  XenModel/Network/IXenConnection.cs
  XenModel/Network/XenConnection.cs
Labels: 2 approvals

#3125 Bumped branding to v4.15. Removed leftover references of branded components.
  Jenkinsfile
  WixInstaller/XenCenter.wxs
  scripts/xenadmin-build.sh
Labels: 2 approvals
