Repository xenserver/xenadmin, pull requests merged in 2023-10, with the labels that each got.

#3233 Generate the xml files without the byte order mark (BOM).
  scripts/xenadmin-build.ps1
Labels: 1 approval

#3238 Disabled unit test for localized resources + CA-383376
  XenAdmin/Wizards/BootModesControl.ja.resx
  XenAdmin/Wizards/BootModesControl.zh-CN.resx
  XenAdmin/Wizards/NewVMWizard/Page_InstallationMedia.ja.resx
  XenAdmin/Wizards/NewVMWizard/Page_InstallationMedia.zh-CN.resx
  XenAdmin/XenAdmin.csproj
  XenAdminTests/CodeTests/AssemblyTests.cs
Labels: 2 approvals, ASAP

#3239 Removed ignored test to fix broken build.
  XenAdminTests/CodeTests/AssemblyTests.cs
Labels: ASAP

#3235 (master) Removed erroneously added backslashes. Generate the xml files without the BOM.
  scripts/xenadmin-build.ps1
Labels: 2 approvals

#3237 CA-381047: Added friendly name for the new capability 'observer'.
  XenModel/FriendlyNames.Designer.cs
  XenModel/FriendlyNames.resx
Labels: 2 approvals

#3236 CA-383650: Removed UI-side-only datasource avg_cpu.
  XenAdmin/Controls/CustomDataGraph/DataSet.cs
  XenAdmin/Controls/CustomDataGraph/GraphList.cs
  XenModel/Actions/GetDataSourcesAction.cs
  XenModel/FriendlyNames.Designer.cs
  XenModel/FriendlyNames.ja.resx
  XenModel/FriendlyNames.resx
  XenModel/FriendlyNames.zh-CN.resx
  XenModel/Utils/Helpers.cs
Labels: 2 approvals

#3242 CA-384191: Fix missing values for min VM restrictions
  XenModel/XenAPI-Extensions/VM.cs
Labels: 1 approval, updated, ASAP

#3244 CA-379971: Ensure `ParallelAction` is not waiting on `_lock` when no actions are running
  XenModel/Actions/ParallelAction.cs
Labels: 2 approvals, ASAP

#3227 CA-383040/XSI-1500: Resume WLB when reverting resolved actions after an update
  XenAdmin/Diagnostics/Checks/AssertCanEvacuateCheck.cs
  XenAdmin/Diagnostics/Checks/HaWlbOffCheck.cs
  XenAdmin/Diagnostics/Problems/PoolProblem/HAEnabledProblem.cs
  XenAdmin/Diagnostics/Problems/PoolProblem/WLBEnabledProblem.cs
  XenAdmin/Wizards/PatchingWizard/PatchingWizard_PrecheckPage.cs
  XenAdmin/Wizards/RollingUpgradeWizard/RollingUpgradeWizardPrecheckPage.cs
  XenModel/Actions/WLB/DisableWLBAction.cs
  XenModel/Messages.Designer.cs
  XenModel/Messages.resx
Labels: 2 approvals

#3153 CP-40844: Adds download source action that gets the latest source code in the production stage
  XenAdmin/Alerts/Types/ClientUpdateAlert.cs
  XenAdmin/Alerts/Types/GuiOldAlert.cs
  XenAdmin/Core/Updates.cs
  XenAdmin/MainWindow.Designer.cs
  XenAdmin/MainWindow.cs
  XenAdmin/MainWindow.resx
  XenAdminTests/UnitTests/AlertTests/XenCenterUpdateAlertTests.cs
  XenModel/Actions/Updates/ClientVersion.cs
  XenModel/Actions/Updates/DownloadFileAction.cs
  XenModel/Actions/Updates/DownloadUpdatesXmlAction.cs
  XenModel/InvisibleMessages.Designer.cs
  XenModel/InvisibleMessages.resx
  XenModel/Messages.Designer.cs
  XenModel/Messages.resx
  XenModel/XenModel.csproj
  scripts/xenadmin-build.ps1
Labels: 2 approvals, ITE
