Repository xenserver/xenadmin, pull requests merged in 2023-09, with the labels that each got.

#3209 CP-40739 (build with VS 2022) and some tech debt
  AddManifest.targets
  CFUValidator/CFUValidator.csproj
  CommandLib/CommandLib.csproj
  README.md
  WixInstaller/XenCenter.wxs
  XenAdmin.sln
  XenAdmin/XenAdmin.csproj
  XenAdmin/app.manifest
  XenAdminTests/XenAdminTests.csproj
  XenCenterLib/XenCenterLib.csproj
  XenModel/XenModel.csproj
  XenOvfApi/XenOvfApi.csproj
  scripts/re-branding.sh
  scripts/xenadmin-build.sh
  xe/Xe.csproj
  xva_verify/Properties/AssemblyInfo.cs
  xva_verify/app.config
  xva_verify/app.manifest
  xva_verify/verify_main.cs
  xva_verify/xva_verify.csproj
  xva_verify/xva_verify.rc
Labels: 2 approvals, ITE

#3212 Refactored retrieval of values from Messages.resx.
  XenAdmin/Controls/Wlb/WlbOptModeScheduler.cs
  XenModel/Actions/Host/HostPowerOnAction.cs
  XenModel/Actions/WLB/InitializeWLBAction.cs
  XenModel/Actions/WLB/RetrieveWlbConfigurationAction.cs
  XenModel/Actions/WLB/SendWlbConfigurationAction.cs
  XenModel/Actions/WLB/WlbReportAction.cs
  XenModel/Messages.Designer.cs
  XenModel/Messages.resx
  XenModel/WLB/WlbOptimizationRecommendation.cs
  XenModel/WLB/WlbServerState.cs
  XenModel/XenModel.csproj
Labels: 2 approvals

#3218 Update links between `CONTRIBUTING` and `MAINTAINERS`
  CONTRIBUTING.md
  MAINTAINERS.md
Labels: 1 approval

#3219 CP-45071: Convert XenCenter build scripts to PowerShell.
  Jenkinsfile
  README.md
  WixInstaller/XenCenter.wxs
  WixInstaller/branding.wxi
  WixInstaller/candleList.txt
  WixInstaller/litList.txt
  WixInstaller/wix_src.patch
  XenAdmin/Alerts/Types/ClientUpdateAlert.cs
  XenAdmin/Core/Registry.cs
  XenAdmin/Program.cs
  XenAdmin/Settings.cs
  XenAdmin/XenAdmin.csproj
  XenAdminTests/CodeTests/AssemblyTests.cs
  XenModel/Actions/StatusReport/ClientSideStatusReportAction.cs
  XenModel/BrandManager.cs
  XenModel/Properties/AssemblyInfo.cs
  scripts/branding.ps1
  scripts/re-branding.sh
  scripts/rebranding.ps1
  scripts/xenadmin-build.ps1
  scripts/xenadmin-build.sh
Labels: 2 approvals

#3220 Build script corrections.
  XenAdmin/TabPages/PerformancePage.cs
  scripts/xenadmin-build.ps1
Labels: 2 approvals, ASAP

#3222 Parse unit "percent" (used by pvsaccelerator_space_utilization). Minor tidy.
  XenAdmin/Controls/CustomDataGraph/DataSet.cs
Labels: 2 approvals

#3184 CA-375900: Prepend `\\?\` to file paths when creating streams for archive generation
  XenAdminTests/ArchiveTests/ArchiveIteratorTests.cs
  XenAdminTests/ArchiveTests/ArchiveWriterTests.cs
  XenCenterLib/Archive/ArchiveIterator.cs
  XenCenterLib/Archive/ArchiveWriter.cs
  XenCenterLib/Archive/TarArchiveWriter.cs
  XenCenterLib/StringUtility.cs
  XenModel/Actions/StatusReport/ZipStatusReportAction.cs
Labels: 1 approval, updated, ASAP

#3224 CA-382850: Catch exception when listing pipe names with invalid characters
  XenCenterLib/NamedPipes.cs
Labels: 2 approvals

#3228 CP-45372: Bumped branding to v5.3
  Jenkinsfile
Labels: 2 approvals

#3211 CP-44767, CP-44766 & CP-44765: Refactor usage of VM restrictions and add `reference_label` to OVFs
  XenAdmin/Commands/ActivateVBDCommand.cs
  XenAdmin/Commands/DeactivateVBDCommand.cs
  XenAdmin/Commands/InstallToolsCommand.cs
  XenAdmin/Commands/VMLifeCycleCommand.cs
  XenAdmin/Controls/Ballooning/VMMemoryControlsBasic.cs
  XenAdmin/Controls/Ballooning/VMMemoryControlsNoEdit.cs
  XenAdmin/Controls/HaNtolControl.cs
  XenAdmin/Controls/NetworkingTab/NetworkList.cs
  XenAdmin/Controls/XenSearch/GroupingControl.cs
  XenAdmin/Controls/XenSearch/QueryElement.cs
  XenAdmin/Diagnostics/Checks/AssertCanEvacuateCheck.cs
  XenAdmin/Dialogs/EvacuateHostDialog.cs
  XenAdmin/Dialogs/VmSnapshotDialog.cs
  XenAdmin/SettingsPanels/EditNetworkPage.cs
  XenAdmin/SettingsPanels/GpuEditPage.cs
  XenAdmin/SettingsPanels/USBEditPage.cs
  XenAdmin/SettingsPanels/VMHAEditPage.cs
  XenAdmin/TabPages/GeneralTabPage.cs
  XenAdmin/Wizards/HAWizard.cs
  XenAdmin/Wizards/HAWizard_Pages/AssignPriorities.cs
  XenAdmin/XenSearch/Columns.cs
  XenAdminTests/SearchTests/VirtualisationStatePropertyQueryTests.cs
  XenModel/Actions/OvfActions/Export.cs
  XenModel/Actions/Pool/EnableHAAction.cs
  XenModel/Actions/VM/HAUnprotectVMAction.cs
  XenModel/Actions/VM/InstallPVToolsAction.cs
  XenModel/Actions/VM/SetHaPrioritiesAction.cs
  XenModel/Utils/Helpers.cs
  XenModel/XenAPI-Extensions/VM.cs
  XenModel/XenSearch/Common.cs
  XenModel/XenSearch/Search.cs
Labels: 1 approval, ITE

#3231 Removed erroneously added backslashes.
  scripts/xenadmin-build.ps1
Labels: 2 approvals, ASAP

#3232 Removed linebreaks in the xmlFormat.
  scripts/xenadmin-build.ps1
Labels: 2 approvals
